import "./globals.css";
import { Fira_Code } from "next/font/google";

const FiraCode = Fira_Code({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Porfolio",
  description: "Generated by Vmhoafng",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={FiraCode.className}>{children}</body>
    </html>
  );
}
